language: go

go:
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install: dep ensure -v

script:
  make run-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
